import '../models/product.dart';

class MockDataService {
  static List<Product> getMockProducts() {
    return [
      // Clothes
      Product(
        id: '1',
        name: 'فستان سهرة أنيق',
        nameEn: 'Elegant Evening Dress',
        description: 'فستان سهرة فاخر مصنوع من أجود أنواع الأقمشة، مناسب للمناسبات الخاصة والحفلات.',
        category: 'clothes',
        priceSYP: 850000,
        priceUSD: 65,
        discountPriceSYP: 680000,
        discountPriceUSD: 52,
        images: [
          'https://images.unsplash.com/photo-1566174053879-31528523f8ae?w=400',
          'https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?w=400',
        ],
        stockQuantity: 15,
        sizes: ['S', 'M', 'L', 'XL'],
        colors: ['أسود', 'أحمر', 'كحلي'],
        rating: 4.8,
        reviewCount: 124,
        isFeatured: true,
        createdAt: DateTime.now().subtract(const Duration(days: 2)),
      ),
      Product(
        id: '2',
        name: 'بلوزة حرير فاخرة',
        nameEn: 'Luxury Silk Blouse',
        description: 'بلوزة من الحرير الطبيعي بتصميم عصري وأنيق.',
        category: 'clothes',
        priceSYP: 420000,
        priceUSD: 32,
        images: [
          'https://images.unsplash.com/photo-1564257631407-4deb1f99d992?w=400',
        ],
        stockQuantity: 30,
        sizes: ['S', 'M', 'L'],
        colors: ['أبيض', 'وردي', 'بيج'],
        rating: 4.5,
        reviewCount: 89,
        isFeatured: true,
        createdAt: DateTime.now().subtract(const Duration(days: 5)),
      ),
      Product(
        id: '3',
        name: 'تنورة ميدي أنيقة',
        nameEn: 'Elegant Midi Skirt',
        description: 'تنورة ميدي بقصة A-line مناسبة للعمل والمناسبات.',
        category: 'clothes',
        priceSYP: 350000,
        priceUSD: 27,
        images: [
          'https://images.unsplash.com/photo-1583496661160-fb5886a0aaaa?w=400',
        ],
        stockQuantity: 25,
        sizes: ['S', 'M', 'L', 'XL'],
        colors: ['أسود', 'رمادي', 'كاميل'],
        rating: 4.3,
        reviewCount: 56,
        createdAt: DateTime.now().subtract(const Duration(days: 3)),
      ),
      Product(
        id: '4',
        name: 'معطف شتوي فاخر',
        nameEn: 'Luxury Winter Coat',
        description: 'معطف شتوي دافئ بتصميم كلاسيكي أنيق.',
        category: 'clothes',
        priceSYP: 1200000,
        priceUSD: 92,
        discountPriceSYP: 960000,
        discountPriceUSD: 74,
        images: [
          'https://images.unsplash.com/photo-1539533018447-63fcce2678e3?w=400',
        ],
        stockQuantity: 10,
        sizes: ['M', 'L', 'XL'],
        colors: ['بيج', 'رمادي', 'كحلي'],
        rating: 4.9,
        reviewCount: 203,
        isFeatured: true,
        createdAt: DateTime.now().subtract(const Duration(days: 1)),
      ),
      // Accessories
      Product(
        id: '5',
        name: 'حقيبة يد جلدية',
        nameEn: 'Leather Handbag',
        description: 'حقيبة يد من الجلد الطبيعي بتصميم عصري وعملي.',
        category: 'accessories',
        priceSYP: 650000,
        priceUSD: 50,
        images: [
          'https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=400',
        ],
        stockQuantity: 20,
        colors: ['أسود', 'بني', 'تان'],
        rating: 4.7,
        reviewCount: 167,
        isFeatured: true,
        createdAt: DateTime.now().subtract(const Duration(days: 4)),
      ),
      Product(
        id: '6',
        name: 'نظارات شمسية أنيقة',
        nameEn: 'Elegant Sunglasses',
        description: 'نظارات شمسية بإطار معدني وعدسات مستقطبة.',
        category: 'accessories',
        priceSYP: 280000,
        priceUSD: 22,
        images: [
          'https://images.unsplash.com/photo-1511499767150-a48a237f0083?w=400',
        ],
        stockQuantity: 40,
        colors: ['ذهبي', 'فضي', 'أسود'],
        rating: 4.4,
        reviewCount: 93,
        createdAt: DateTime.now().subtract(const Duration(days: 6)),
      ),
      Product(
        id: '7',
        name: 'حزام جلد إيطالي',
        nameEn: 'Italian Leather Belt',
        description: 'حزام من الجلد الإيطالي الفاخر مع إبزيم معدني.',
        category: 'accessories',
        priceSYP: 180000,
        priceUSD: 14,
        images: [
          'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=400',
        ],
        stockQuantity: 35,
        sizes: ['S', 'M', 'L'],
        colors: ['أسود', 'بني'],
        rating: 4.6,
        reviewCount: 78,
        createdAt: DateTime.now().subtract(const Duration(days: 7)),
      ),
      Product(
        id: '8',
        name: 'وشاح حرير مطبوع',
        nameEn: 'Printed Silk Scarf',
        description: 'وشاح من الحرير الناعم بطبعات زهور أنيقة.',
        category: 'accessories',
        priceSYP: 220000,
        priceUSD: 17,
        discountPriceSYP: 176000,
        discountPriceUSD: 14,
        images: [
          'https://images.unsplash.com/photo-1601924921557-45e8e0891c8f?w=400',
        ],
        stockQuantity: 50,
        colors: ['متعدد الألوان'],
        rating: 4.2,
        reviewCount: 45,
        isFeatured: true,
        createdAt: DateTime.now().subtract(const Duration(days: 8)),
      ),
      // Jewelry
      Product(
        id: '9',
        name: 'عقد ذهبي فاخر',
        nameEn: 'Luxury Gold Necklace',
        description: 'عقد ذهبي عيار 21 بتصميم دمشقي تقليدي.',
        category: 'jewelry',
        priceSYP: 3500000,
        priceUSD: 269,
        images: [
          'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?w=400',
        ],
        stockQuantity: 5,
        rating: 5.0,
        reviewCount: 312,
        isFeatured: true,
        createdAt: DateTime.now().subtract(const Duration(days: 1)),
      ),
      Product(
        id: '10',
        name: 'أساور فضية مزخرفة',
        nameEn: 'Ornate Silver Bracelets',
        description: 'مجموعة أساور فضية بنقوش شرقية مميزة.',
        category: 'jewelry',
        priceSYP: 450000,
        priceUSD: 35,
        images: [
          'https://images.unsplash.com/photo-1573408301185-9146fe634ad0?w=400',
        ],
        stockQuantity: 18,
        rating: 4.6,
        reviewCount: 98,
        createdAt: DateTime.now().subtract(const Duration(days: 9)),
      ),
      Product(
        id: '11',
        name: 'خاتم ألماس أنيق',
        nameEn: 'Elegant Diamond Ring',
        description: 'خاتم من الذهب الأبيض مرصع بالألماس الطبيعي.',
        category: 'jewelry',
        priceSYP: 5200000,
        priceUSD: 400,
        images: [
          'https://images.unsplash.com/photo-1605100804763-247f67b3557e?w=400',
        ],
        stockQuantity: 3,
        sizes: ['6', '7', '8', '9'],
        rating: 4.9,
        reviewCount: 187,
        isFeatured: true,
        createdAt: DateTime.now().subtract(const Duration(days: 2)),
      ),
      Product(
        id: '12',
        name: 'أقراط لؤلؤ طبيعي',
        nameEn: 'Natural Pearl Earrings',
        description: 'أقراط من اللؤلؤ الطبيعي مع إطار ذهبي.',
        category: 'jewelry',
        priceSYP: 780000,
        priceUSD: 60,
        discountPriceSYP: 624000,
        discountPriceUSD: 48,
        images: [
          'https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?w=400',
        ],
        stockQuantity: 12,
        rating: 4.7,
        reviewCount: 134,
        createdAt: DateTime.now().subtract(const Duration(days: 10)),
      ),
    ];
  }
}
